let bgObject = new RectObject();
bgObject.baseStyle.isUseFill = true;
bgObject.baseStyle.fillType = ColorType.Solid;
bgObject.baseStyle.fillColor = 0xffffff;
bgObject.baseStyle.fillAlpha = 1.0;
bgObject.baseStyle.isUseLine = false;
bgObject.baseStyle.isUseText = false;
bgObject.w = 1920.0;
bgObject.h = 1080.0;
bgObject.anchor.h = 0.0;
bgObject.anchor.v = 0.0;
bgObject.point.x = 0.0;
bgObject.point.y = 0.0;
bgObject.addAt(app.stage);
layoutObjects.push(bgObject);

let titleObject = new RectObject();
titleObject.baseStyle.isUseFill = true;
titleObject.baseStyle.fillType = ColorType.Solid;
titleObject.baseStyle.fillColor = 0x8AA6F9;
titleObject.baseStyle.fillAlpha = 1.0;
titleObject.baseStyle.isUseLine = false;
titleObject.baseStyle.isUseText = false;
titleObject.w = 1920.0;
titleObject.h = 180.0;
titleObject.anchor.h = 0.0;
titleObject.anchor.v = 0.0;
titleObject.point.x = 0.0;
titleObject.point.y = 0.0;
titleObject.addAt(app.stage);
layoutObjects.push(titleObject);

let timeBgObject = new RoundRectObject();
timeBgObject.roundTip = 20.0;
timeBgObject.baseStyle.isUseFill = true;
timeBgObject.baseStyle.fillType = ColorType.Solid;
timeBgObject.baseStyle.fillColor = 0xC3C3C3;
timeBgObject.baseStyle.fillAlpha = 1.0;
timeBgObject.baseStyle.isUseLine = false;
timeBgObject.baseStyle.isUseText = false;
timeBgObject.w = 300.0;
timeBgObject.h = 150.0;
timeBgObject.anchor.h = 0.0;
timeBgObject.anchor.v = 0.0;
timeBgObject.point.x = 15.0;
timeBgObject.point.y = 15.0;
timeBgObject.addAt(app.stage);
layoutObjects.push(timeBgObject);

let time1Object = new RectObject();
time1Object.baseStyle.isUseFill = false;
time1Object.baseStyle.isUseLine = false;
time1Object.baseStyle.isUseText = true;
time1Object.baseStyle.text = "01/01/2023";
time1Object.baseStyle.fontColor = 0x000000;
time1Object.baseStyle.fontSize = 40.0;
time1Object.baseStyle.isFontBold = false;
time1Object.baseStyle.textAnchor.h = 0.5;
time1Object.baseStyle.textAnchor.v = 0.5;
time1Object.baseStyle.isReadable = true;
time1Object.w = 300.0;
time1Object.h = 75.0;
time1Object.anchor.h = 0.0;
time1Object.anchor.v = 0.0;
time1Object.point.x = 15.0;
time1Object.point.y = 20.0;
time1Object.addAt(app.stage);
layoutObjects.push(time1Object);

let time2Object = new RectObject();
time2Object.baseStyle.isUseFill = false;
time2Object.baseStyle.isUseLine = false;
time2Object.baseStyle.isUseText = true;
time2Object.baseStyle.text = "12:34:56";
time2Object.baseStyle.fontColor = 0x000000;
time2Object.baseStyle.fontSize = 40.0;
time2Object.baseStyle.isFontBold = false;
time2Object.baseStyle.textAnchor.h = 0.5;
time2Object.baseStyle.textAnchor.v = 0.5;
time2Object.baseStyle.isReadable = true;
time2Object.w = 300.0;
time2Object.h = 75.0;
time2Object.anchor.h = 0.0;
time2Object.anchor.v = 0.0;
time2Object.point.x = 15.0;
time2Object.point.y = 85.0;
time2Object.addAt(app.stage);
layoutObjects.push(time2Object);

let title1Object = new RectObject();
title1Object.baseStyle.isUseFill = false;
title1Object.baseStyle.isUseLine = false;
title1Object.baseStyle.isUseText = true;
title1Object.baseStyle.text = "Welcome to Soekarno Hatta International Airport";
title1Object.baseStyle.fontColor = 0x000000;
title1Object.baseStyle.fontSize = 32.0;
title1Object.baseStyle.isFontBold = false;
title1Object.baseStyle.textAnchor.h = 0.5;
title1Object.baseStyle.textAnchor.v = 0.5;
title1Object.baseStyle.isReadable = true;
title1Object.w = 1920.0;
title1Object.h = 80.0;
title1Object.anchor.h = 0.0;
title1Object.anchor.v = 0.0;
title1Object.point.x = 0.0;
title1Object.point.y = 0.0;
title1Object.addAt(app.stage);
layoutObjects.push(title1Object);

let title2Object = new RectObject();
title2Object.baseStyle.isUseFill = false;
title2Object.baseStyle.isUseLine = false;
title2Object.baseStyle.isUseText = true;
title2Object.baseStyle.text = "TERMINAL IB";
title2Object.baseStyle.fontColor = 0x000000;
title2Object.baseStyle.fontSize = 62.0;
title2Object.baseStyle.isFontBold = false;
title2Object.baseStyle.textAnchor.h = 0.5;
title2Object.baseStyle.textAnchor.v = 0.5;
title2Object.baseStyle.isReadable = true;
title2Object.w = 1920.0;
title2Object.h = 80.0;
title2Object.anchor.h = 0.0;
title2Object.anchor.v = 0.0;
title2Object.point.x = 0.0;
title2Object.point.y = 80.0;
title2Object.addAt(app.stage);
layoutObjects.push(title2Object);

let lnObject = new RectObject();
lnObject.baseStyle.isUseFill = true;
lnObject.baseStyle.fillType = ColorType.Solid;
lnObject.baseStyle.fillColor = 0x000000;
lnObject.baseStyle.fillAlpha = 1.0;
lnObject.baseStyle.isUseLine = false;
lnObject.baseStyle.isUseText = false;
lnObject.w = 1920.0;
lnObject.h = 20.0;
lnObject.anchor.h = 0.0;
lnObject.anchor.v = 0.0;
lnObject.point.x = 0.0;
lnObject.point.y = 180.0;
lnObject.addAt(app.stage);
layoutObjects.push(lnObject);

let hdObject = new RectObject();
hdObject.baseStyle.isUseFill = true;
hdObject.baseStyle.fillType = ColorType.Solid;
hdObject.baseStyle.fillColor = 0x99D9EA;
hdObject.baseStyle.fillAlpha = 1.0;
hdObject.baseStyle.isUseLine = false;
hdObject.baseStyle.isUseText = false;
hdObject.w = 1920.0;
hdObject.h = 100.0;
hdObject.anchor.h = 0.0;
hdObject.anchor.v = 0.0;
hdObject.point.x = 0.0;
hdObject.point.y = 200.0;
hdObject.addAt(app.stage);
layoutObjects.push(hdObject);

let hd1Object = new RectObject();
hd1Object.baseStyle.isUseFill = false;
hd1Object.baseStyle.isUseLine = false;
hd1Object.baseStyle.isUseText = true;
hd1Object.baseStyle.text = "Departure Time";
hd1Object.baseStyle.fontColor = 0x000000;
hd1Object.baseStyle.fontSize = 38.0;
hd1Object.baseStyle.isFontBold = true;
hd1Object.baseStyle.textAnchor.h = 0.5;
hd1Object.baseStyle.textAnchor.v = 0.5;
hd1Object.baseStyle.isReadable = true;
hd1Object.w = 480.0;
hd1Object.h = 100.0;
hd1Object.anchor.h = 0.0;
hd1Object.anchor.v = 0.0;
hd1Object.point.x = 0.0;
hd1Object.point.y = 200.0;
hd1Object.addAt(app.stage);
layoutObjects.push(hd1Object);

let hd2Object = new RectObject();
hd2Object.baseStyle.isUseFill = false;
hd2Object.baseStyle.isUseLine = false;
hd2Object.baseStyle.isUseText = true;
hd2Object.baseStyle.text = "Destination";
hd2Object.baseStyle.fontColor = 0x000000;
hd2Object.baseStyle.fontSize = 38.0;
hd2Object.baseStyle.isFontBold = true;
hd2Object.baseStyle.textAnchor.h = 0.5;
hd2Object.baseStyle.textAnchor.v = 0.5;
hd2Object.baseStyle.isReadable = true;
hd2Object.w = 480.0;
hd2Object.h = 100.0;
hd2Object.anchor.h = 0.0;
hd2Object.anchor.v = 0.0;
hd2Object.point.x = 480.0;
hd2Object.point.y = 200.0;
hd2Object.addAt(app.stage);
layoutObjects.push(hd2Object);

let hd3Object = new RectObject();
hd3Object.baseStyle.isUseFill = false;
hd3Object.baseStyle.isUseLine = false;
hd3Object.baseStyle.isUseText = true;
hd3Object.baseStyle.text = "Platform";
hd3Object.baseStyle.fontColor = 0x000000;
hd3Object.baseStyle.fontSize = 38.0;
hd3Object.baseStyle.isFontBold = true;
hd3Object.baseStyle.textAnchor.h = 0.5;
hd3Object.baseStyle.textAnchor.v = 0.5;
hd3Object.baseStyle.isReadable = true;
hd3Object.w = 480.0;
hd3Object.h = 100.0;
hd3Object.anchor.h = 0.0;
hd3Object.anchor.v = 0.0;
hd3Object.point.x = 960.0;
hd3Object.point.y = 200.0;
hd3Object.addAt(app.stage);
layoutObjects.push(hd3Object);

let hd4Object = new RectObject();
hd4Object.baseStyle.isUseFill = false;
hd4Object.baseStyle.isUseLine = false;
hd4Object.baseStyle.isUseText = true;
hd4Object.baseStyle.text = "Arrival Time";
hd4Object.baseStyle.fontColor = 0x000000;
hd4Object.baseStyle.fontSize = 38.0;
hd4Object.baseStyle.isFontBold = true;
hd4Object.baseStyle.textAnchor.h = 0.5;
hd4Object.baseStyle.textAnchor.v = 0.5;
hd4Object.baseStyle.isReadable = true;
hd4Object.w = 480.0;
hd4Object.h = 100.0;
hd4Object.anchor.h = 0.0;
hd4Object.anchor.v = 0.0;
hd4Object.point.x = 1440.0;
hd4Object.point.y = 200.0;
hd4Object.addAt(app.stage);
layoutObjects.push(hd4Object);

let bdr1c1Object = new RectObject();
bdr1c1Object.baseStyle.isUseFill = false;
bdr1c1Object.baseStyle.isUseLine = false;
bdr1c1Object.baseStyle.isUseText = true;
bdr1c1Object.baseStyle.text = "01:00";
bdr1c1Object.baseStyle.fontColor = 0x000000;
bdr1c1Object.baseStyle.fontSize = 38.0;
bdr1c1Object.baseStyle.isFontBold = false;
bdr1c1Object.baseStyle.textAnchor.h = 0.5;
bdr1c1Object.baseStyle.textAnchor.v = 0.5;
bdr1c1Object.baseStyle.isReadable = true;
bdr1c1Object.w = 480.0;
bdr1c1Object.h = 170.0;
bdr1c1Object.anchor.h = 0.0;
bdr1c1Object.anchor.v = 0.0;
bdr1c1Object.point.x = 0.0;
bdr1c1Object.point.y = 300.0;
bdr1c1Object.addAt(app.stage);
layoutObjects.push(bdr1c1Object);

let bdr1c2Object = new RectObject();
bdr1c2Object.baseStyle.isUseFill = false;
bdr1c2Object.baseStyle.isUseLine = false;
bdr1c2Object.baseStyle.isUseText = true;
bdr1c2Object.baseStyle.text = "Terminal 1";
bdr1c2Object.baseStyle.fontColor = 0x000000;
bdr1c2Object.baseStyle.fontSize = 38.0;
bdr1c2Object.baseStyle.isFontBold = false;
bdr1c2Object.baseStyle.textAnchor.h = 0.5;
bdr1c2Object.baseStyle.textAnchor.v = 0.5;
bdr1c2Object.baseStyle.isReadable = true;
bdr1c2Object.baseStyle.isTextCrop = true;
bdr1c2Object.baseStyle.isTextAutoScroll = true;
bdr1c2Object.w = 480.0;
bdr1c2Object.h = 170.0;
bdr1c2Object.anchor.h = 0.0;
bdr1c2Object.anchor.v = 0.0;
bdr1c2Object.point.x = 480.0;
bdr1c2Object.point.y = 300.0;
bdr1c2Object.addAt(app.stage);
layoutObjects.push(bdr1c2Object);

let bdr1c3Object = new RectObject();
bdr1c3Object.baseStyle.isUseFill = false;
bdr1c3Object.baseStyle.isUseLine = false;
bdr1c3Object.baseStyle.isUseText = true;
bdr1c3Object.baseStyle.text = "A";
bdr1c3Object.baseStyle.fontColor = 0x000000;
bdr1c3Object.baseStyle.fontSize = 38.0;
bdr1c3Object.baseStyle.isFontBold = false;
bdr1c3Object.baseStyle.textAnchor.h = 0.5;
bdr1c3Object.baseStyle.textAnchor.v = 0.5;
bdr1c3Object.baseStyle.isReadable = true;
bdr1c3Object.w = 480.0;
bdr1c3Object.h = 170.0;
bdr1c3Object.anchor.h = 0.0;
bdr1c3Object.anchor.v = 0.0;
bdr1c3Object.point.x = 960.0;
bdr1c3Object.point.y = 300.0;
bdr1c3Object.addAt(app.stage);
layoutObjects.push(bdr1c3Object);

let bdr1c4Object = new RectObject();
bdr1c4Object.baseStyle.isUseFill = false;
bdr1c4Object.baseStyle.isUseLine = false;
bdr1c4Object.baseStyle.isUseText = true;
bdr1c4Object.baseStyle.text = "5 Minutes";
bdr1c4Object.baseStyle.fontColor = 0x000000;
bdr1c4Object.baseStyle.fontSize = 38.0;
bdr1c4Object.baseStyle.isFontBold = false;
bdr1c4Object.baseStyle.textAnchor.h = 0.5;
bdr1c4Object.baseStyle.textAnchor.v = 0.5;
bdr1c4Object.baseStyle.isReadable = true;
bdr1c4Object.w = 480.0;
bdr1c4Object.h = 170.0;
bdr1c4Object.anchor.h = 0.0;
bdr1c4Object.anchor.v = 0.0;
bdr1c4Object.point.x = 1440.0;
bdr1c4Object.point.y = 300.0;
bdr1c4Object.addAt(app.stage);
layoutObjects.push(bdr1c4Object);

let bdr2c1Object = new RectObject();
bdr2c1Object.baseStyle.isUseFill = false;
bdr2c1Object.baseStyle.isUseLine = false;
bdr2c1Object.baseStyle.isUseText = true;
bdr2c1Object.baseStyle.text = "02:00";
bdr2c1Object.baseStyle.fontColor = 0x000000;
bdr2c1Object.baseStyle.fontSize = 38.0;
bdr2c1Object.baseStyle.isFontBold = false;
bdr2c1Object.baseStyle.textAnchor.h = 0.5;
bdr2c1Object.baseStyle.textAnchor.v = 0.5;
bdr2c1Object.baseStyle.isReadable = true;
bdr2c1Object.w = 480.0;
bdr2c1Object.h = 170.0;
bdr2c1Object.anchor.h = 0.0;
bdr2c1Object.anchor.v = 0.0;
bdr2c1Object.point.x = 0.0;
bdr2c1Object.point.y = 470.0;
bdr2c1Object.addAt(app.stage);
layoutObjects.push(bdr2c1Object);

let bdr2c2Object = new RectObject();
bdr2c2Object.baseStyle.isUseFill = false;
bdr2c2Object.baseStyle.isUseLine = false;
bdr2c2Object.baseStyle.isUseText = true;
bdr2c2Object.baseStyle.text = "Terminal 2";
bdr2c2Object.baseStyle.fontColor = 0x000000;
bdr2c2Object.baseStyle.fontSize = 38.0;
bdr2c2Object.baseStyle.isFontBold = false;
bdr2c2Object.baseStyle.textAnchor.h = 0.5;
bdr2c2Object.baseStyle.textAnchor.v = 0.5;
bdr2c2Object.baseStyle.isReadable = true;
bdr2c2Object.baseStyle.isTextCrop = true;
bdr2c2Object.baseStyle.isTextAutoScroll = true;
bdr2c2Object.w = 480.0;
bdr2c2Object.h = 170.0;
bdr2c2Object.anchor.h = 0.0;
bdr2c2Object.anchor.v = 0.0;
bdr2c2Object.point.x = 480.0;
bdr2c2Object.point.y = 470.0;
bdr2c2Object.addAt(app.stage);
layoutObjects.push(bdr2c2Object);

let bdr2c3Object = new RectObject();
bdr2c3Object.baseStyle.isUseFill = false;
bdr2c3Object.baseStyle.isUseLine = false;
bdr2c3Object.baseStyle.isUseText = true;
bdr2c3Object.baseStyle.text = "B";
bdr2c3Object.baseStyle.fontColor = 0x000000;
bdr2c3Object.baseStyle.fontSize = 38.0;
bdr2c3Object.baseStyle.isFontBold = false;
bdr2c3Object.baseStyle.textAnchor.h = 0.5;
bdr2c3Object.baseStyle.textAnchor.v = 0.5;
bdr2c3Object.baseStyle.isReadable = true;
bdr2c3Object.w = 480.0;
bdr2c3Object.h = 170.0;
bdr2c3Object.anchor.h = 0.0;
bdr2c3Object.anchor.v = 0.0;
bdr2c3Object.point.x = 960.0;
bdr2c3Object.point.y = 470.0;
bdr2c3Object.addAt(app.stage);
layoutObjects.push(bdr2c3Object);

let bdr2c4Object = new RectObject();
bdr2c4Object.baseStyle.isUseFill = false;
bdr2c4Object.baseStyle.isUseLine = false;
bdr2c4Object.baseStyle.isUseText = true;
bdr2c4Object.baseStyle.text = "1 Hour";
bdr2c4Object.baseStyle.fontColor = 0x000000;
bdr2c4Object.baseStyle.fontSize = 38.0;
bdr2c4Object.baseStyle.isFontBold = false;
bdr2c4Object.baseStyle.textAnchor.h = 0.5;
bdr2c4Object.baseStyle.textAnchor.v = 0.5;
bdr2c4Object.baseStyle.isReadable = true;
bdr2c4Object.w = 480.0;
bdr2c4Object.h = 170.0;
bdr2c4Object.anchor.h = 0.0;
bdr2c4Object.anchor.v = 0.0;
bdr2c4Object.point.x = 1440.0;
bdr2c4Object.point.y = 470.0;
bdr2c4Object.addAt(app.stage);
layoutObjects.push(bdr2c4Object);

let bdr3c1Object = new RectObject();
bdr3c1Object.baseStyle.isUseFill = false;
bdr3c1Object.baseStyle.isUseLine = false;
bdr3c1Object.baseStyle.isUseText = true;
bdr3c1Object.baseStyle.text = "03:00";
bdr3c1Object.baseStyle.fontColor = 0x000000;
bdr3c1Object.baseStyle.fontSize = 38.0;
bdr3c1Object.baseStyle.isFontBold = false;
bdr3c1Object.baseStyle.textAnchor.h = 0.5;
bdr3c1Object.baseStyle.textAnchor.v = 0.5;
bdr3c1Object.baseStyle.isReadable = true;
bdr3c1Object.w = 480.0;
bdr3c1Object.h = 170.0;
bdr3c1Object.anchor.h = 0.0;
bdr3c1Object.anchor.v = 0.0;
bdr3c1Object.point.x = 0.0;
bdr3c1Object.point.y = 640.0;
bdr3c1Object.addAt(app.stage);
layoutObjects.push(bdr3c1Object);

let bdr3c2Object = new RectObject();
bdr3c2Object.baseStyle.isUseFill = false;
bdr3c2Object.baseStyle.isUseLine = false;
bdr3c2Object.baseStyle.isUseText = true;
bdr3c2Object.baseStyle.text = "Terminal 3";
bdr3c2Object.baseStyle.fontColor = 0x000000;
bdr3c2Object.baseStyle.fontSize = 38.0;
bdr3c2Object.baseStyle.isFontBold = false;
bdr3c2Object.baseStyle.textAnchor.h = 0.5;
bdr3c2Object.baseStyle.textAnchor.v = 0.5;
bdr3c2Object.baseStyle.isReadable = true;
bdr3c2Object.baseStyle.isTextCrop = true;
bdr3c2Object.baseStyle.isTextAutoScroll = true;
bdr3c2Object.w = 480.0;
bdr3c2Object.h = 170.0;
bdr3c2Object.anchor.h = 0.0;
bdr3c2Object.anchor.v = 0.0;
bdr3c2Object.point.x = 480.0;
bdr3c2Object.point.y = 640.0;
bdr3c2Object.addAt(app.stage);
layoutObjects.push(bdr3c2Object);

let bdr3c3Object = new RectObject();
bdr3c3Object.baseStyle.isUseFill = false;
bdr3c3Object.baseStyle.isUseLine = false;
bdr3c3Object.baseStyle.isUseText = true;
bdr3c3Object.baseStyle.text = "C";
bdr3c3Object.baseStyle.fontColor = 0x000000;
bdr3c3Object.baseStyle.fontSize = 38.0;
bdr3c3Object.baseStyle.isFontBold = false;
bdr3c3Object.baseStyle.textAnchor.h = 0.5;
bdr3c3Object.baseStyle.textAnchor.v = 0.5;
bdr3c3Object.baseStyle.isReadable = true;
bdr3c3Object.w = 480.0;
bdr3c3Object.h = 170.0;
bdr3c3Object.anchor.h = 0.0;
bdr3c3Object.anchor.v = 0.0;
bdr3c3Object.point.x = 960.0;
bdr3c3Object.point.y = 640.0;
bdr3c3Object.addAt(app.stage);
layoutObjects.push(bdr3c3Object);

let bdr3c4Object = new RectObject();
bdr3c4Object.baseStyle.isUseFill = false;
bdr3c4Object.baseStyle.isUseLine = false;
bdr3c4Object.baseStyle.isUseText = true;
bdr3c4Object.baseStyle.text = "2 Hours";
bdr3c4Object.baseStyle.fontColor = 0x000000;
bdr3c4Object.baseStyle.fontSize = 38.0;
bdr3c4Object.baseStyle.isFontBold = false;
bdr3c4Object.baseStyle.textAnchor.h = 0.5;
bdr3c4Object.baseStyle.textAnchor.v = 0.5;
bdr3c4Object.baseStyle.isReadable = true;
bdr3c4Object.w = 480.0;
bdr3c4Object.h = 170.0;
bdr3c4Object.anchor.h = 0.0;
bdr3c4Object.anchor.v = 0.0;
bdr3c4Object.point.x = 1440.0;
bdr3c4Object.point.y = 640.0;
bdr3c4Object.addAt(app.stage);
layoutObjects.push(bdr3c4Object);

let bdr4c1Object = new RectObject();
bdr4c1Object.baseStyle.isUseFill = false;
bdr4c1Object.baseStyle.isUseLine = false;
bdr4c1Object.baseStyle.isUseText = true;
bdr4c1Object.baseStyle.text = "04:00";
bdr4c1Object.baseStyle.fontColor = 0x000000;
bdr4c1Object.baseStyle.fontSize = 38.0;
bdr4c1Object.baseStyle.isFontBold = false;
bdr4c1Object.baseStyle.textAnchor.h = 0.5;
bdr4c1Object.baseStyle.textAnchor.v = 0.5;
bdr4c1Object.baseStyle.isReadable = true;
bdr4c1Object.w = 480.0;
bdr4c1Object.h = 170.0;
bdr4c1Object.anchor.h = 0.0;
bdr4c1Object.anchor.v = 0.0;
bdr4c1Object.point.x = 0.0;
bdr4c1Object.point.y = 810.0;
bdr4c1Object.addAt(app.stage);
layoutObjects.push(bdr4c1Object);

let bdr4c2Object = new RectObject();
bdr4c2Object.baseStyle.isUseFill = false;
bdr4c2Object.baseStyle.isUseLine = false;
bdr4c2Object.baseStyle.isUseText = true;
bdr4c2Object.baseStyle.text = "Terminal 4";
bdr4c2Object.baseStyle.fontColor = 0x000000;
bdr4c2Object.baseStyle.fontSize = 38.0;
bdr4c2Object.baseStyle.isFontBold = false;
bdr4c2Object.baseStyle.textAnchor.h = 0.5;
bdr4c2Object.baseStyle.textAnchor.v = 0.5;
bdr4c2Object.baseStyle.isReadable = true;
bdr4c2Object.baseStyle.isTextCrop = true;
bdr4c2Object.baseStyle.isTextAutoScroll = true;
bdr4c2Object.w = 480.0;
bdr4c2Object.h = 170.0;
bdr4c2Object.anchor.h = 0.0;
bdr4c2Object.anchor.v = 0.0;
bdr4c2Object.point.x = 480.0;
bdr4c2Object.point.y = 810.0;
bdr4c2Object.addAt(app.stage);
layoutObjects.push(bdr4c2Object);

let bdr4c3Object = new RectObject();
bdr4c3Object.baseStyle.isUseFill = false;
bdr4c3Object.baseStyle.isUseLine = false;
bdr4c3Object.baseStyle.isUseText = true;
bdr4c3Object.baseStyle.text = "D";
bdr4c3Object.baseStyle.fontColor = 0x000000;
bdr4c3Object.baseStyle.fontSize = 38.0;
bdr4c3Object.baseStyle.isFontBold = false;
bdr4c3Object.baseStyle.textAnchor.h = 0.5;
bdr4c3Object.baseStyle.textAnchor.v = 0.5;
bdr4c3Object.baseStyle.isReadable = true;
bdr4c3Object.w = 480.0;
bdr4c3Object.h = 170.0;
bdr4c3Object.anchor.h = 0.0;
bdr4c3Object.anchor.v = 0.0;
bdr4c3Object.point.x = 960.0;
bdr4c3Object.point.y = 810.0;
bdr4c3Object.addAt(app.stage);
layoutObjects.push(bdr4c3Object);

let bdr4c4Object = new RectObject();
bdr4c4Object.baseStyle.isUseFill = false;
bdr4c4Object.baseStyle.isUseLine = false;
bdr4c4Object.baseStyle.isUseText = true;
bdr4c4Object.baseStyle.text = "3 Hours";
bdr4c4Object.baseStyle.fontColor = 0x000000;
bdr4c4Object.baseStyle.fontSize = 38.0;
bdr4c4Object.baseStyle.isFontBold = false;
bdr4c4Object.baseStyle.textAnchor.h = 0.5;
bdr4c4Object.baseStyle.textAnchor.v = 0.5;
bdr4c4Object.baseStyle.isReadable = true;
bdr4c4Object.w = 480.0;
bdr4c4Object.h = 170.0;
bdr4c4Object.anchor.h = 0.0;
bdr4c4Object.anchor.v = 0.0;
bdr4c4Object.point.x = 1440.0;
bdr4c4Object.point.y = 810.0;
bdr4c4Object.addAt(app.stage);
layoutObjects.push(bdr4c4Object);

let ftObject = new RectObject();
ftObject.baseStyle.isUseFill = true;
ftObject.baseStyle.fillType = ColorType.Solid;
ftObject.baseStyle.fillColor = 0xC3C3C3;
ftObject.baseStyle.fillAlpha = 1.0;
ftObject.baseStyle.isUseLine = false;
ftObject.baseStyle.isUseText = false;
ftObject.w = 1920.0;
ftObject.h = 100.0;
ftObject.anchor.h = 0.0;
ftObject.anchor.v = 0.0;
ftObject.point.x = 0.0;
ftObject.point.y = 980.0;
ftObject.addAt(app.stage);
layoutObjects.push(ftObject);

let ft1Object = new RectObject();
ft1Object.a = (0 * Math.PI) / 180;
ft1Object.baseStyle.isUseFill = false;
ft1Object.baseStyle.isUseLine = false;
ft1Object.baseStyle.isUseText = true;
ft1Object.baseStyle.text = "Welcome Passenger • this is Station Passenger Information Display • by Len Railway Systems • Please Be Aware of Your Luggage • Welcome Passenger • this is Station Passenger Information Display • by Len Railway Systems • Please Be Aware of Your Luggage";
ft1Object.baseStyle.fontColor = 0x000000;
ft1Object.baseStyle.fontSize = 32.0;
ft1Object.baseStyle.isFontBold = false;
ft1Object.baseStyle.textAnchor.h = 0.0;
ft1Object.baseStyle.textAnchor.v = 0.5;
ft1Object.baseStyle.isReadable = true;
ft1Object.baseStyle.isTextCrop = true;
ft1Object.baseStyle.isTextAutoScroll = true;
ft1Object.w = 1920;
ft1Object.h = 100.0;
ft1Object.anchor.h = 0.0;
ft1Object.anchor.v = 0.0;
ft1Object.point.x = 0.0;
ft1Object.point.y = 980.0;
ft1Object.addAt(app.stage);
layoutObjects.push(ft1Object);

//

function pad(n) {
    return (n < 10) ? ("0" + n) : n;
}

function setClock() {
    const today = new Date();
    const date = pad(today.getDate())+'/'+pad(today.getMonth()+1)+'/'+today.getFullYear();
    const time = pad(today.getHours())+":"+pad(today.getMinutes())+":"+pad(today.getSeconds());
    time1Object.baseStyle.text = date;
    time2Object.baseStyle.text = time;
}

function relativeTime(today, current) {
    const ms = current.getTime() - today.getTime();
    if (ms <= 1000 * 60) {
        return "now";
    } else if (ms <= 1000 * 60 * 60) {
        return Math.floor(ms/(1000 * 60)) + " minutes";
    } else if (ms < 1000 * 60 * 60 * 2) {
        return Math.floor(ms/(1000 * 60 * 60)) + " hour";
    } else if (ms <= 1000 * 60 * 60 * 24) {
        return Math.floor(ms/(1000 * 60 * 60)) + " hours";
    } else if (ms < 1000 * 60 * 60 * 24 * 2) {
        return Math.floor(ms/(1000 * 60 * 60 * 24)) + " day";
    }
    return Math.floor(ms/(1000 * 60 * 60 * 24)) + " days";
}

function refreshData() {
    const today = new Date();
    const hh = today.getHours();
    const mm = today.getMinutes();

    const baseH = today.getHours() + ((mm > 0) ? 1 : 0);

    bdr1c1Object.baseStyle.text = pad((baseH + 0)%24) + ":00";
    bdr2c1Object.baseStyle.text = pad((baseH + 1)%24) + ":00";
    bdr3c1Object.baseStyle.text = pad((baseH + 2)%24) + ":00";
    bdr4c1Object.baseStyle.text = pad((baseH + 3)%24) + ":00";
    
    bdr1c2Object.baseStyle.text = ((baseH + 0)%2 == 0) ? "Terminal 1" : "Terminal 2  ➜ Terminal 3";
    bdr2c2Object.baseStyle.text = ((baseH + 1)%2 == 0) ? "Terminal 1" : "Terminal 2  ➜ Terminal 3";
    bdr3c2Object.baseStyle.text = ((baseH + 2)%2 == 0) ? "Terminal 1" : "Terminal 2  ➜ Terminal 3";
    bdr4c2Object.baseStyle.text = ((baseH + 3)%2 == 0) ? "Terminal 1" : "Terminal 2  ➜ Terminal 3";
    
    bdr1c3Object.baseStyle.text = ((baseH + 0)%2 == 0) ? "A" : "B";
    bdr2c3Object.baseStyle.text = ((baseH + 1)%2 == 0) ? "A" : "B";
    bdr3c3Object.baseStyle.text = ((baseH + 2)%2 == 0) ? "A" : "B";
    bdr4c3Object.baseStyle.text = ((baseH + 3)%2 == 0) ? "A" : "B";

    bdr1c4Object.baseStyle.text = relativeTime(today, new Date(today.getFullYear(), today.getMonth(), today.getDate(), baseH + 0, -5));
    bdr2c4Object.baseStyle.text = relativeTime(today, new Date(today.getFullYear(), today.getMonth(), today.getDate(), baseH + 1, -5));
    bdr3c4Object.baseStyle.text = relativeTime(today, new Date(today.getFullYear(), today.getMonth(), today.getDate(), baseH + 2, -5));
    bdr4c4Object.baseStyle.text = relativeTime(today, new Date(today.getFullYear(), today.getMonth(), today.getDate(), baseH + 3, -5));
}

// setInterval(function() {
//     setClock();
//     refreshLayoutView();
// }, 1000/120);

app.ticker.add(() => {
    setClock();
    refreshData();
    // scale = 0.35;
    refreshLayoutView();
});